CMamba_v1: 'CryptoMamba/v1.yaml'
CMamba_v2: 'CryptoMamba/v2.yaml'
CMamba_v3: 'CryptoMamba/v3.yaml'
CMamba_v4: 'CryptoMamba/v4.yaml'
CMamba_v5: 'CryptoMamba/v5.yaml'
CMamba_test: 'CryptoMamba/test.yaml'
LSTM_nv: 'LSTM/lstm_nv.yaml'
LSTM_v: 'LSTM/lstm_v.yaml'
iTransformer_v: 'iTransformer/itransformer_v.yaml'
iTransformer_v: 'iTransformer/itransformer_nv.yaml'